"""empty message

Revision ID: 1e3501b97976
Revises: 2cec9694a271
Create Date: 2018-06-20 06:33:10.677273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3501b97976'
down_revision = '2cec9694a271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_link_visited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_link_visited')
    # ### end Alembic commands ###
